name: flutter_firebase_instagram
description: Flutter Firebase Instagram

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  firebase_storage: ^10.2.17
  get: ^4.6.5
  flutter_screenutil: ^5.5.3+2
  image_picker: ^0.8.5+3
  video_player: ^2.4.2
  timeago: ^3.2.2
  share_plus: ^4.0.4
  flutter_slidable: ^1.3.0
  visibility_detector: ^0.3.3
  keyboard_dismisser: ^3.0.0
  path: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Cookie-Regular
      fonts:
        - asset: assets/fonts/Cookie-Regular.ttf
    - family: Lato-Regular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf